### ISSUE TITLE
SPb Fprog

### ISSUE THREAD

**Issue by niquola** [rigidus/moto#3]
Михаил извени, что беспокою :)

Как насчет выступить на фп митапе 16 января

**Comment by rigidus** [comment]
Не вопрос, мой телефон +7 911 286 92 90

**Comment by niquola** [comment]
Подготовится успеешь к 16?

пришли название доклада и краткое описание и зарегся -
http://spb-fp-meetup.timepad.ru/event/174162/ (для проходной)

73's nicola

**Comment by rigidus** [comment]
Успею скорее всего. Я зарегистрировался, куда присылать название и описание?

**Comment by niquola** [comment]
Мне письмом - niquola@gmail.com

2015-01-14 1:34 GMT+03:00 Rigidus <notifications@github.com>:

**Comment by rigidus** [comment]
Отослал

**Comment by rigidus** [comment]
2015-01-14 1:35 GMT+03:00 niquola <notifications@github.com>:
